CREATE TABLE IF NOT EXISTS scores (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    score INT NOT NULL,
    version VARCHAR(20) NOT NULL,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);